parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
env:
  browser: true
  es2021: true
plugins:
  - '@typescript-eslint'
  - functional
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules: {}