env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  camelcase: 0
  import/extensions: 0 # FIXME: remove when rule is adjusted for new nodejs version
  import/prefer-default-export: 0
  no-console: 0
  no-unused-vars: 0
  no-underscore-dangle: 0
